// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IOdosSharesRouter
/// @notice Interface for buying PlayerSharePool shares with alternative tokens via Odos.
/// @dev Uses Odos Router V3 (0x0D05a7D3448512B78fa8A9e46c4872C88C4a0D05) for swaps.
interface IOdosSharesRouter {
    struct SharesOrder {
        bytes16 orderId;
        address recipient;
        address pool;
        address inputToken;      // address(0) = native ETH
        uint256 inputAmount;
        uint256 minSharesOut;
        uint256 minUsdcOut;      // Slippage protection for the swap
        uint256 expiry;
    }

    /// @notice Data for executing the swap via Odos Router V3
    /// @dev Generated by the Odos API: POST /sor/quote/v2 + POST /sor/assemble
    struct OdosSwapParams {
        bytes swapData;          // transaction.data from the Odos /sor/assemble API
        uint256 valueToSend;     // transaction.value (0 for ERC20, inputAmount for ETH)
    }

    // --- Events ---
    event SharesPurchased(
        bytes16 indexed orderId,
        address indexed buyer,
        address indexed pool,
        address inputToken,
        uint256 inputAmount,
        uint256 usdcReceived,
        uint256 sharesOut,
        address signer
    );

    // --- Main Functions ---
    function claimOrder(
        SharesOrder calldata order,
        bytes calldata signature,
        OdosSwapParams calldata odosParams
    ) external payable returns (uint256 sharesOut);

    function previewPurchase(address pool, uint256 usdcAmount) 
        external 
        view 
        returns (uint256 sharesOut, uint256 effectiveUsdc);

    // --- Views ---
    function ODOS_ROUTER_V3() external pure returns (address);
    function supportedPools(address pool) external view returns (bool);
    function supportedTokens(address token) external view returns (bool);
    function spreadBps() external view returns (uint256);
    function treasury() external view returns (address);
    function domainSeparator() external view returns (bytes32);
}
