// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IRefundableRaffle
/// @notice Interface for the refundable raffle backed by USDC ticket deposits.
interface IRefundableRaffle {
    // --- Enums ---
    enum Phase {
        Inactive,       // Raffle not started yet
        Deposit,        // Accepting deposits
        Drawing,        // Deposits closed, waiting for the draw
        Claiming,       // Draw completed, prizes/refunds can be claimed
        Closed          // Raffle finished
    }

    // --- Structs ---
    struct UserInfo {
        uint256 depositedAmount;    // USDC deposited
        uint256 ticketCount;        // Tickets obtained
        bool claimed;               // Whether the refund has been claimed
    }

    struct DepositOrder {
        bytes16 orderId;        // Unique order ID (generated by the backend)
        address recipient;      // Who receives the tickets
        uint256 usdcAmount;     // USDC amount to deposit
        uint256 expiry;         // Order expiry timestamp
    }

    // --- Events ---
    /// @notice Emitted when a deposit order is executed.
    event OrderCreated(
        bytes16 indexed orderId,
        address indexed user,
        uint256 amount,
        uint256 ticketCount,
        uint256 firstTicketId,
        uint256 lastTicketId
    );
    event PhaseChanged(Phase oldPhase, Phase newPhase);
    event WinnersDrawn(uint256 totalWinningTickets, bytes32 merkleRoot);
    event RefundClaimed(address indexed user, uint256 refundAmount);
    event DepositScheduled(uint256 startTime, uint256 endTime);
    event DepositDurationChanged(uint256 newDuration);
    event DepositEndTimeChanged(uint256 newEndTime);
    event RaffleCancelled(bool fullRefund, uint256 refundedAmount);

    // --- Errors ---
    error InvalidPhase();
    error InvalidAmount();
    error ZeroAddress();
    error AlreadyClaimed();
    error NoTickets();
    error DepositTooSmall();
    error InvalidMerkleProof();
    error DepositPeriodEnded();
    error DepositNotStarted();
    error UnauthorizedExecutor();
    error OrderExpired();
    error OrderAlreadyConsumed();
    error InvalidSignature();
    error ExceedsMaxTicketsPerOrder();

    // --- User Functions ---

    /// @notice Executes a backend-signed deposit order.
    /// @param order The deposit order.
    /// @param signature EIP-712 signature of the order.
    /// @return ticketsMinted Number of tickets created.
    function executeDepositOrder(DepositOrder calldata order, bytes calldata signature) 
        external 
        returns (uint256 ticketsMinted);

    /// @notice Claims a refund for losing tickets using a Merkle proof.
    /// @dev Only losers can claim. Winners are handled off-chain.
    /// @param losingTicketCount Number of losing tickets to refund.
    /// @param merkleProof Proof to verify the data against the Merkle tree.
    function claimRefund(
        uint256 losingTicketCount,
        bytes32[] calldata merkleProof
    ) external;

    // --- View Functions ---

    /// @notice Returns the current raffle phase.
    function currentPhase() external view returns (Phase);

    /// @notice Returns user info for the given address.
    function getUserInfo(address user) external view returns (UserInfo memory);

    /// @notice Returns the total number of tickets issued.
    function totalTickets() external view returns (uint256);

    // --- Admin Functions ---

    /// @notice Starts the deposit phase with a scheduled start.
    /// @param startTime Start timestamp (0 = now, future = scheduled).
    function startDeposit(uint256 startTime) external;

    /// @notice Sets the deposit phase duration (only before the phase starts).
    /// @param duration Duration in seconds.
    function setDepositDuration(uint256 duration) external;

    /// @notice Closes deposits and moves to the drawing phase.
    function closeDeposits() external;

    /// @notice Returns the number of winners drawn so far.
    function drawnWinnersCount() external view returns (uint256);

    /// @notice Commits the Merkle root for refunds computed off-chain.
    /// @param merkleRoot Root of the Merkle tree (leaves = keccak256(abi.encode(user, refundAmount))).
    /// @param totalWinners Total number of winning tickets (max 50000).
    function commitWinners(bytes32 merkleRoot, uint256 totalWinners) external;

    /// @notice Closes the raffle and allows withdrawal of remaining funds.
    function closeRaffle() external;

    /// @notice Withdraws the USDC prize pool funds (admin only).
    function withdrawPrizePool() external;
}
