// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {Pausable} from "@openzeppelin/contracts/utils/Pausable.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import {EIP712} from "@openzeppelin/contracts/utils/cryptography/EIP712.sol";

import {MathUtils} from "../libraries/MathUtils.sol";

/// @title IPlayerSharePool
/// @notice Minimal interface for PlayerSharePool admin functions
interface IPlayerSharePoolAdmin {
    function adminTransferShares(address from, address to, uint256 amount) external;
    function currentPrice() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function treasury() external view returns (address);
}

/**
 * @title OdosSharesRouter
 * @notice Allows purchasing PlayerSharePool shares by paying with alternative tokens (ETH, WETH, other stablecoins).
 * @dev Uses Odos Router V3 to swap the input token into USDC, then transfers shares from the treasury.
 * 
 * Odos Router V3:
 * - Unified address across all chains: 0x0D05a7D3448512B78fa8A9e46c4872C88C4a0D05
 * - Audited by Zellic (2025)
 * - The API directly generates the transaction calldata
 * 
 * Flow:
 * 1. Backend calls Odos API (/sor/quote/v3 + /sor/assemble) to obtain transaction.data
 * 2. Backend generates an EIP-712 signed order with swap data
 * 3. User calls claimOrder with order + signature + odosParams
 * 4. Contract executes the swap via low-level call to Odos router
 * 5. Contract transfers shares from the treasury to the user
 * 6. USDC goes to the treasury
 */
contract OdosSharesRouter is AccessControl, ReentrancyGuard, Pausable, EIP712 {
    using SafeERC20 for IERC20;

    // --- Errors ---
    error RouterZeroAddress();
    error RouterZeroValue();
    error RouterOrderExpired();
    error RouterOrderConsumed();
    error RouterInvalidSignature();
    error RouterUnauthorizedExecutor();
    error RouterInsufficientOutput();
    error RouterSlippageExceeded();
    error RouterInsufficientTreasuryShares();
    error RouterPoolNotSupported();
    error RouterTokenNotSupported();
    error RouterSwapFailed();

    // --- Roles ---
    bytes32 public constant OPERATOR_ROLE = keccak256("OPERATOR_ROLE");
    bytes32 public constant ORDER_SIGNER_ROLE = keccak256("ORDER_SIGNER_ROLE");

    // --- Constants ---
    uint256 private constant FEE_DENOMINATOR = 10_000;
    uint256 private constant MAX_TTL = 1 hours;
    address private constant ETH = address(0);
    
    /// @notice Odos Router V3 - Unified address across all supported EVM chains
    /// @dev Audited by Zellic (2025). See: https://docs.odos.xyz/build/contracts
    address public constant ODOS_ROUTER_V3 = 0x0D05a7D3448512B78fa8A9e46c4872C88C4a0D05;

    // --- EIP-712 TypeHash ---
    bytes32 private constant SHARES_ORDER_TYPEHASH = keccak256(
        "SharesOrder(bytes16 orderId,address recipient,address pool,address inputToken,uint256 inputAmount,uint256 minSharesOut,uint256 minUsdcOut,uint256 expiry)"
    );

    // --- Structs ---
    struct SharesOrder {
        bytes16 orderId;
        address recipient;
        address pool;
        address inputToken;      // Token paid by the user (address(0) = native ETH)
        uint256 inputAmount;     // Amount of tokens to spend
        uint256 minSharesOut;    // Minimum guaranteed shares
        uint256 minUsdcOut;      // Minimum USDC from swap (slippage protection)
        uint256 expiry;
    }

    /// @notice Data for executing the swap via Odos Router V3
    /// @dev Generated by the Odos API: POST /sor/quote/v3 + POST /sor/assemble
    struct OdosSwapParams {
        bytes swapData;          // transaction.data from Odos API /sor/assemble
        uint256 valueToSend;     // transaction.value (0 for ERC20, inputAmount for ETH)
    }

    // --- State ---
    IERC20 public immutable usdc;
    address public treasury;
    
    /// @notice Spread/fee in bps retained by the broker (e.g. 100 = 1%)
    uint256 public spreadBps;

    /// @notice Supported pools: poolAddress => enabled
    mapping(address => bool) public supportedPools;

    /// @notice Supported tokens for purchases: tokenAddress => enabled (address(0) = ETH)
    mapping(address => bool) public supportedTokens;

    /// @notice Already consumed orders
    mapping(bytes16 => bool) public consumedOrders;

    // --- Events ---
    event SharesPurchased(
        bytes16 indexed orderId,
        address indexed buyer,
        address indexed pool,
        address inputToken,
        uint256 inputAmount,
        uint256 usdcReceived,
        uint256 sharesOut,
        address signer
    );
    event PoolSupportUpdated(address indexed pool, bool supported);
    event TokenSupportUpdated(address indexed token, bool supported);
    event SpreadUpdated(uint256 oldSpread, uint256 newSpread);
    event TreasuryUpdated(address indexed oldTreasury, address indexed newTreasury);
    event EmergencyWithdraw(address indexed token, address indexed to, uint256 amount);

    /// @notice Initializes the router with base parameters.
    /// @dev Uses Odos Router V3 at fixed address 0x0D05a7D3448512B78fa8A9e46c4872C88C4a0D05
    /// @param _admin Admin account with all initial roles.
    /// @param _orderSigner Account authorized to sign orders.
    /// @param _usdc USDC token address (swap output).
    /// @param _treasury Treasury address that holds shares and receives USDC.
    /// @param _spreadBps Initial spread in basis points.
    constructor(
        address _admin,
        address _orderSigner,
        address _usdc,
        address _treasury,
        uint256 _spreadBps
    ) EIP712("OdosSharesRouter", "1") {
        if (_admin == address(0)) revert RouterZeroAddress();
        if (_orderSigner == address(0)) revert RouterZeroAddress();
        if (_usdc == address(0)) revert RouterZeroAddress();
        if (_treasury == address(0)) revert RouterZeroAddress();

        usdc = IERC20(_usdc);
        treasury = _treasury;
        spreadBps = _spreadBps;

        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(OPERATOR_ROLE, _admin);
        _grantRole(ORDER_SIGNER_ROLE, _orderSigner);
    }

    /// @notice Receives ETH for native swaps
    receive() external payable {}

    // =============================================================
    //                        MAIN FUNCTIONS
    // =============================================================

    /// @notice Executes a signed order: swaps token to USDC via Odos V3, transfers shares.
    /// @param order Order with input token, target pool, minimum shares.
    /// @param signature EIP-712 signature from ORDER_SIGNER_ROLE.
    /// @param odosParams Odos V3 swap data (generated by the API: /sor/quote/v3 + /sor/assemble).
    /// @return sharesOut Amount of shares transferred to the user.
    function claimOrder(
        SharesOrder calldata order,
        bytes calldata signature,
        OdosSwapParams calldata odosParams
    )
        external
        payable
        nonReentrant
        whenNotPaused
        returns (uint256 sharesOut)
    {
        // --- Validations ---
        if (msg.sender != order.recipient) revert RouterUnauthorizedExecutor();
        if (order.inputAmount == 0) revert RouterZeroValue();
        if (order.minSharesOut == 0) revert RouterZeroValue();
        if (order.minUsdcOut == 0) revert RouterZeroValue();
        if (!supportedPools[order.pool]) revert RouterPoolNotSupported();
        if (!supportedTokens[order.inputToken]) revert RouterTokenNotSupported();
        
        _validateOrderWindow(order.expiry);
        if (consumedOrders[order.orderId]) revert RouterOrderConsumed();

        // Verify signature
        bytes32 digest = _hashOrder(order);
        address signer = ECDSA.recover(digest, signature);
        if (!hasRole(ORDER_SIGNER_ROLE, signer)) revert RouterInvalidSignature();

        consumedOrders[order.orderId] = true;

        // --- Input token transfer and swap ---
        uint256 usdcReceived;
        
        if (order.inputToken == ETH) {
            // Native ETH
            if (msg.value != order.inputAmount) revert RouterZeroValue();
            usdcReceived = _swapViaOdosV3(
                order.inputToken,
                order.inputAmount,
                odosParams,
                true // isETH
            );
        } else {
            // ERC20
            if (msg.value != 0) revert RouterZeroValue(); // Do not send ETH for ERC20 swaps
            IERC20(order.inputToken).safeTransferFrom(msg.sender, address(this), order.inputAmount);
            usdcReceived = _swapViaOdosV3(
                order.inputToken,
                order.inputAmount,
                odosParams,
                false // isETH
            );
        }

        // Verify USDC slippage
        if (usdcReceived < order.minUsdcOut) revert RouterInsufficientOutput();

        // --- Calculate shares ---
        // Apply spread
        uint256 spreadAmount = (usdcReceived * spreadBps) / FEE_DENOMINATOR;
        uint256 effectiveUsdc = usdcReceived - spreadAmount;

        // Calculate shares based on the pool's current price
        IPlayerSharePoolAdmin pool = IPlayerSharePoolAdmin(order.pool);
        uint256 currentPrice = pool.currentPrice();
        if (currentPrice == 0) revert RouterInsufficientOutput();

        // shares = (effectiveUsdc * 1e6) / price
        sharesOut = MathUtils.mulDiv(effectiveUsdc, 1e6, currentPrice, MathUtils.Rounding.Down);

        // Verify shares slippage
        if (sharesOut < order.minSharesOut) revert RouterSlippageExceeded();

        // Verify that the treasury has sufficient shares
        address poolTreasury = pool.treasury();
        if (pool.balanceOf(poolTreasury) < sharesOut) revert RouterInsufficientTreasuryShares();

        // --- Transfer shares from treasury to user ---
        pool.adminTransferShares(poolTreasury, order.recipient, sharesOut);

        // --- Transfer USDC to treasury ---
        usdc.safeTransfer(treasury, usdcReceived);

        emit SharesPurchased(
            order.orderId,
            order.recipient,
            order.pool,
            order.inputToken,
            order.inputAmount,
            effectiveUsdc,
            sharesOut,
            signer
        );

        return sharesOut;
    }

    /// @notice Purchase preview: calculates estimated shares given equivalent USDC.
    /// @param pool PlayerSharePool address.
    /// @param usdcAmount Equivalent USDC after the swap.
    /// @return sharesOut Estimated shares.
    /// @return effectiveUsdc USDC net of spread.
    function previewPurchase(address pool, uint256 usdcAmount) 
        external 
        view 
        returns (uint256 sharesOut, uint256 effectiveUsdc) 
    {
        if (!supportedPools[pool] || usdcAmount == 0) return (0, 0);

        uint256 spreadAmount = (usdcAmount * spreadBps) / FEE_DENOMINATOR;
        effectiveUsdc = usdcAmount - spreadAmount;

        IPlayerSharePoolAdmin sharePool = IPlayerSharePoolAdmin(pool);
        uint256 currentPrice = sharePool.currentPrice();
        if (currentPrice == 0) return (0, effectiveUsdc);

        sharesOut = MathUtils.mulDiv(effectiveUsdc, 1e6, currentPrice, MathUtils.Rounding.Down);
    }

    // =============================================================
    //                      INTERNAL FUNCTIONS
    // =============================================================

    /// @dev Executes the swap via Odos Router V3 using low-level call
    /// @param inputToken Input token (address(0) for ETH)
    /// @param inputAmount Amount of tokens to swap
    /// @param odosParams Swap data generated by the Odos API
    /// @param isETH True if the input is native ETH
    /// @return usdcReceived Amount of USDC received from the swap
    function _swapViaOdosV3(
        address inputToken,
        uint256 inputAmount,
        OdosSwapParams calldata odosParams,
        bool isETH
    ) internal returns (uint256 usdcReceived) {
        uint256 balanceBefore = usdc.balanceOf(address(this));

        if (!isETH) {
            // Approve Odos Router V3 for ERC20
            IERC20(inputToken).approve(ODOS_ROUTER_V3, inputAmount);
        }

        // Execute the swap via low-level call to Odos Router V3
        // Calldata generated by the Odos API (/sor/assemble -> transaction.data)
        (bool success, ) = ODOS_ROUTER_V3.call{value: odosParams.valueToSend}(
            odosParams.swapData
        );

        if (!success) {
            revert RouterSwapFailed();
        }

        usdcReceived = usdc.balanceOf(address(this)) - balanceBefore;

        if (!isETH) {
            // Reset approval for safety
            IERC20(inputToken).approve(ODOS_ROUTER_V3, 0);
        }

        return usdcReceived;
    }

    function _validateOrderWindow(uint256 expiry) internal view {
        if (expiry == 0 || block.timestamp > expiry) revert RouterOrderExpired();
        if (expiry - block.timestamp > MAX_TTL) revert RouterOrderExpired();
    }

    function _hashOrder(SharesOrder calldata order) internal view returns (bytes32) {
        return _hashTypedDataV4(
            keccak256(
                abi.encode(
                    SHARES_ORDER_TYPEHASH,
                    order.orderId,
                    order.recipient,
                    order.pool,
                    order.inputToken,
                    order.inputAmount,
                    order.minSharesOut,
                    order.minUsdcOut,
                    order.expiry
                )
            )
        );
    }

    // =============================================================
    //                      ADMIN FUNCTIONS
    // =============================================================

    /// @notice Enables/disables a PlayerSharePool for purchases.
    /// @param pool Pool address.
    /// @param supported True to enable, false to disable.
    function setPoolSupported(address pool, bool supported) 
        external 
        onlyRole(OPERATOR_ROLE) 
    {
        if (pool == address(0)) revert RouterZeroAddress();
        supportedPools[pool] = supported;
        emit PoolSupportUpdated(pool, supported);
    }

    /// @notice Enables/disables a token for purchases.
    /// @param token Token address (address(0) for native ETH).
    /// @param supported True to enable, false to disable.
    function setTokenSupported(address token, bool supported) 
        external 
        onlyRole(OPERATOR_ROLE) 
    {
        supportedTokens[token] = supported;
        emit TokenSupportUpdated(token, supported);
    }

    /// @notice Updates the broker spread.
    /// @param _spreadBps New spread in basis points (max 500 = 5%).
    function setSpread(uint256 _spreadBps) 
        external 
        onlyRole(DEFAULT_ADMIN_ROLE) 
    {
        require(_spreadBps <= 500, "Spread too high");
        uint256 oldSpread = spreadBps;
        spreadBps = _spreadBps;
        emit SpreadUpdated(oldSpread, _spreadBps);
    }

    /// @notice Updates the treasury address.
    /// @param _treasury New treasury address.
    function setTreasury(address _treasury) 
        external 
        onlyRole(DEFAULT_ADMIN_ROLE) 
    {
        if (_treasury == address(0)) revert RouterZeroAddress();
        address oldTreasury = treasury;
        treasury = _treasury;
        emit TreasuryUpdated(oldTreasury, _treasury);
    }

    /// @notice Pauses the contract.
    function pause() external onlyRole(DEFAULT_ADMIN_ROLE) {
        _pause();
    }

    /// @notice Unpauses the contract.
    function unpause() external onlyRole(DEFAULT_ADMIN_ROLE) {
        _unpause();
    }

    /// @notice Withdraws stuck tokens in emergency (admin only, paused only).
    /// @param token Token address (address(0) for ETH).
    /// @param to Recipient.
    /// @param amount Amount to withdraw (0 = full balance).
    function emergencyWithdraw(address token, address to, uint256 amount)
        external
        onlyRole(DEFAULT_ADMIN_ROLE)
        whenPaused
    {
        if (to == address(0)) revert RouterZeroAddress();
        
        if (token == ETH) {
            uint256 balance = address(this).balance;
            uint256 toSend = amount == 0 ? balance : amount;
            (bool success, ) = payable(to).call{value: toSend}("");
            require(success, "ETH transfer failed");
            emit EmergencyWithdraw(token, to, toSend);
        } else {
            uint256 balance = IERC20(token).balanceOf(address(this));
            uint256 toSend = amount == 0 ? balance : amount;
            IERC20(token).safeTransfer(to, toSend);
            emit EmergencyWithdraw(token, to, toSend);
        }
    }

    // =============================================================
    //                      VIEW FUNCTIONS
    // =============================================================

    /// @notice Returns the EIP-712 domain separator for off-chain verification.
    function domainSeparator() external view returns (bytes32) {
        return _domainSeparatorV4();
    }
}
